# Generated by Django 3.0.3 on 2020-05-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerword',
            name='username',
        ),
        migrations.AddField(
            model_name='offerword',
            name='letter',
            field=models.CharField(choices=[('a', 'a'), ('e', 'e'), ('ı', 'ı'), ('i', 'i'), ('u', 'u'), ('ü', 'ü'), ('o', 'o'), ('ö', 'ö')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
