# Generated by Django 3.0.3 on 2020-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20200518_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerword',
            name='listenAudioFile',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
