# Generated by Django 3.0.3 on 2020-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_offerword_listenaudiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerword',
            name='wordName',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
