# Generated by Django 3.0.3 on 2020-05-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('file_audio', models.FileField(upload_to='musics/')),
                ('file_word_audio', models.FileField(upload_to='musics/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WordAudioRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_word_audio', models.FileField(upload_to='musics/')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='user.Offer')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='user.User'),
        ),
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_audio', models.FileField(upload_to='musics/')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='user.Offer')),
            ],
        ),
    ]
